const VOCAB_FOOD = {
  "Fruits 🍎": [
    "apple", "banana", "orange", "mango", "watermelon", "strawberry", "grape", "pineapple", "peach", "pear", "cherry", "lemon", "lime", "coconut", "papaya",
    "kiwi", "blueberry", "raspberry", "blackberry", "pomegranate", "avocado", "melon", "plum", "apricot", "fig", "guava", "lychee", "durian", "dragonfruit", "passionfruit",
    "grapefruit", "tangerine", "mandarin", "nectarine", "cranberry", "cantaloupe", "persimmon", "date", "raisin", "olive", "clementine", "pomelo", "starfruit", "jackfruit", "longan",
    "rambutan", "mangosteen", "soursop", "custard apple", "mulberry", "gooseberry", "elderberry", "boysenberry", "blackcurrant", "redcurrant", "quince", "kumquat", "tamarind", "breadfruit", "plantain",
    "salak", "sapodilla", "cherimoya", "prickly pear", "honeydew", "rockmelon", "cloudberry", "bilberry", "feijoa", "loquat", "mamey", "physalis", "sugar apple", "white peach", "yellow watermelon",
    "pink grapefruit", "golden kiwi", "red banana", "rose apple", "wax apple", "water apple", "Java plum", "blood orange", "finger lime", "cactus pear", "miracle fruit", "ice apple", "horned melon", "pawpaw", "medlar",
    "jabuticaba", "mangaba", "pepino", "dewberry", "serviceberry", "satsuma", "yuzu", "bergamot", "damson", "salmonberry", "acai", "ackee", "ambarella", "atemoya", "bael",
    "bignay", "bilimbi", "black sapote", "Burmese grape", "cacao", "camu camu", "canistel", "cape gooseberry", "cashew apple", "cempedak", "chayote", "chico", "coffee cherry", "cocona", "cupuacu",
    "curuba", "emblic", "etrog", "galia melon", "gac", "genip", "goji berry", "governor's plum", "grumichama", "guanabana", "guarana", "hackberry", "hardy kiwi", "hog plum", "huckleberry",
    "icaco", "imbe", "Indian fig", "jaboticaba", "jambolan", "jujube", "junglesop", "kaffir lime", "kakadu plum", "kecapi", "kei apple", "kitembilla", "korlan", "kiwano", "langsat",
    "lanzones", "lemon drop mangosteen", "limequat", "lingonberry", "longkong", "lucuma", "mabolo", "mammee apple", "marionberry", "marula", "mayapple", "melon pear", "mirabelle", "muntries", "nance",
    "naranjilla", "noni", "ohelo berry", "otaheite apple", "pili", "pitanga", "plumcot", "pulasan", "quenepa", "red mombin", "rimu", "safou", "santol", "sapote", "sea buckthorn",
    "soncoya", "sour cherry", "tamarillo", "tayberry", "ugli fruit", "wampee", "white sapote", "wolfberry", "ximenia", "yellow mombin", "abiu", "alligator apple", "alpine strawberry", "amazon grape", "araza",
    "bacuri", "barbados cherry", "beach plum", "black cherry", "blue honeysuckle", "acerola", "African cherry orange", "African mango", "akebi", "amla", "apple berry", "Asian pear", "azarole", "babaco", "banana passionfruit"
  ],

  "Vegetables 🥦": [
    "carrot", "potato", "tomato", "cucumber", "broccoli", "cabbage", "spinach", "lettuce", "onion", "garlic", "pumpkin", "corn", "mushroom", "eggplant", "celery",
    "peas", "bean", "radish", "asparagus", "cauliflower", "sweet potato", "kale", "bok choy", "spring onion", "leek", "turnip", "beetroot", "zucchini", "bell pepper", "chili",
    "ginger", "okra", "artichoke", "avocado", "yam", "cassava", "taro", "watercress", "rocket", "arugula", "mustard greens", "collard greens", "brussels sprouts", "snow peas", "green beans",
    "broad beans", "kidney beans", "chickpeas", "lentils", "soybean", "edamame", "bamboo shoots", "bean sprouts", "lotus root", "bitter melon", "chayote", "jicama", "parsnip", "fennel", "shallot",
    "scallion", "water chestnut", "sweetcorn", "butternut squash", "acorn squash", "spaghetti squash", "turnip greens", "swiss chard", "endive", "radicchio", "cress", "dandelion greens", "seaweed", "nori", "kombu",
    "wakame", "moringa", "daikon", "burdock", "sunchoke", "rutabaga", "kohlrabi", "plantain", "poblano pepper", "jalapeno", "serrano pepper", "habanero", "napa cabbage", "red cabbage", "savoy cabbage",
    "romaine lettuce", "iceberg lettuce", "butter lettuce", "water spinach", "amaranth leaves", "beet greens", "carrot greens", "mustard spinach", "komatsuna", "tatsoi", "mizuna", "purslane", "sorrel", "land cress", "garden cress",
    "fiddlehead fern", "hearts of palm", "banana flower", "lotus stem", "malanga", "yucca", "turmeric", "galangal", "horseradish", "wasabi", "parsley root", "celeriac", "Hamburg parsley", "skirret", "salsify",
    "scorzonera", "water caltrop", "Jerusalem artichoke", "Chinese artichoke", "globe artichoke", "cardoon", "sea kale", "purple sprouting broccoli", "broccolini", "broccoflower", "romanesco", "cauliflower greens", "Chinese broccoli", "yu choy", "rapini",
    "broccoli leaves", "red onion", "white onion", "yellow onion", "pearl onion", "pickling onion", "garlic scape", "green garlic", "ramps", "wild leek", "elephant garlic", "chives", "garlic chives", "chive flowers", "garlic bulb",
    "amaranth", "arrowhead", "ash gourd", "banana squash", "bitter gourd", "bottle gourd", "broccoli rabe", "cabbage sprouts", "calabash", "cassava leaves", "chicory", "Chinese cabbage", "Chinese celery", "Chinese eggplant", "cilantro",
    "cowpea", "crookneck squash", "delicata squash", "drumstick", "fava beans", "gai lan", "golden beet", "green bell pepper", "hubbard squash", "Italian parsley", "kabocha squash", "lamb's lettuce", "mache", "Malabar spinach", "mung beans",
    "onion sprouts", "oyster mushroom", "pattypan squash", "pea shoots", "pinto beans", "red leaf lettuce", "snap peas", "snow pea shoots", "split peas", "squash blossoms", "sugar snap peas", "sweet pepper", "tomatillo", "yardlong beans", "zucchini blossom",
    "black-eyed pea", "bok choy sum", "butterhead lettuce", "cabbage turnip", "cactus pad", "calabrese", "celtuce", "cherry tomato", "chili pepper", "cluster beans", "collard", "coriander", "corn salad", "cremini mushroom", "daikon sprout",
    "earth chestnut", "Egyptian onion", "elephant ear", "fava bean", "fennel bulb", "fiddlehead", "fingerling potato", "Florence fennel", "garden pea", "gherkin", "giant puffball", "gobo", "grape tomato", "green onion", "green soybean",
    "horseradish root", "lambsquarters", "leaf lettuce", "lemongrass", "lentil sprouts", "lima bean", "mangetout", "mung bean sprouts", "mustard seed", "nira", "nopales", "okra pod", "onion bulb", "oyster plant", "parsnip root",
    "pepperoncini", "petit pois", "pickle", "pimiento", "pinto bean", "podded pea", "pointed cabbage", "potato onion", "prairie turnip", "radish pod", "red leaf chicory", "runner bean", "salsify root", "scallion bulb", "sea asparagus",
    "sea bean", "sea grape", "sea lettuce", "shallot bulb", "shell pea", "shiitake", "snake gourd", "soybean sprout", "spinach beet", "sugar pea", "summer squash", "taro root", "teardrop tomato", "tree ear mushroom", "turnip root",
    "water bamboo", "water convolvulus", "water mimosa", "wax gourd", "white radish", "wild asparagus", "winged bean", "winter melon", "yam bean", "yellow squash", "zucchini flower", "amaranth seed", "artichoke heart", "asparagus bean", "bamboo shoot",
    "beet leaf", "bitter cucumber", "black radish", "broccoli florets", "cabbage leaf", "carrot top", "cauliflower floret", "celery stalk", "chayote squash", "cherry pepper", "chickpea sprout", "chive blossom", "collard leaf", "cress leaf", "curly kale"
  ],

  "Food 🍔": [
    "pizza", "burger", "sandwich", "noodles", "pasta", "rice", "sushi", "curry", "soup", "steak", "sausage", "pancake", "waffle", "toast", "salad",
    "dumpling", "fried chicken", "hotdog", "lasagna", "burrito", "taco", "nachos", "fries", "meatball", "omelette", "scrambled eggs", "fried rice", "ramen", "spring roll", "fish and chips",
    "chicken rice", "fried noodles", "macaroni", "spaghetti", "risotto", "gnocchi", "paella", "kimchi", "hummus", "falafel", "tempura", "quesadilla", "focaccia", "croissant", "pretzel",
    "bruschetta", "bibimbap", "satay", "laksa", "ceviche", "fondue", "kebab", "shawarma", "dim sum", "roast chicken", "barbecue", "hotpot", "porridge", "cereal", "bacon",
    "ham", "cheese", "yogurt", "bread", "butter", "egg", "tofu", "beans", "corn", "mashed potato", "baked potato", "chicken wings", "fishball", "meatloaf", "crab cake",
    "clam chowder", "garlic bread", "coleslaw", "stuffing", "quiche", "tortilla", "bolognese", "carbonara", "teriyaki", "yakitori", "sashimi", "udon", "soba", "takoyaki", "churros",
    "oatmeal", "granola", "muesli", "french toast", "bagel", "muffin", "scone", "biscuit", "gravy", "hash browns", "breakfast burrito", "eggs benedict", "crepe", "danish", "cinnamon roll",
    "donut", "coffee cake", "English muffin", "crumpet", "grits", "corned beef hash", "kippers", "black pudding", "baked beans", "bubble and squeak", "full English breakfast", "avocado toast", "smoothie bowl", "acai bowl", "yogurt parfait",
    "granola bar", "protein bar", "toastie", "panini", "croque monsieur", "croque madame", "Monte Cristo", "grilled cheese", "BLT", "club sandwich", "Reuben", "pastrami sandwich", "meatball sub", "chicken wrap", "veggie wrap",
    "falafel wrap", "shawarma wrap", "gyro", "souvlaki", "pita", "piadina", "arepa", "pupusa", "empanada", "tamale", "enchilada", "fajita", "tostada", "gordita", "chimichanga",
    "taquito", "flauta", "elote", "esquites", "guacamole", "salsa", "pico de gallo", "queso", "nacho cheese", "refried beans", "Mexican rice", "cilantro lime rice", "carnitas", "barbacoa", "al pastor",
    "birria", "cochinita pibil", "chilaquiles", "huevos rancheros", "migas", "breakfast taco", "breakfast quesadilla", "breakfast sandwich", "sausage roll", "pasty", "Cornish pasty", "samosa", "pakora", "bhaji", "dosa",
    "idli", "vada", "uttapam", "upma", "poha", "biryani", "pulao", "khichdi", "dal", "sambar", "rasam", "tikka masala", "butter chicken", "chicken tikka", "tandoori chicken",
    "kofta", "seekh kebab", "shish kebab", "doner kebab", "baba ganoush", "tabbouleh", "fattoush", "dolma", "kibbeh", "sarma", "manti", "borek", "gozleme", "lahmacun", "pide",
    "menemen", "shakshuka", "couscous", "tagine", "harira", "merguez", "ras el hanout", "injera", "doro wat", "tibs", "kitfo", "jollof rice", "fufu", "ugali", "nyama choma",
    "bobotie", "bunny chow", "chakalaka", "pap", "sadza", "nsima", "wat", "misir wot", "shiro", "gomen", "fasolia", "atkilt", "alicha", "sega wat", "dulet",
    "gored gored", "tere sega", "ayibe", "buticha", "chechebsa", "firfir", "genfo", "kocho", "bulla", "ambasha", "himbasha", "dabo", "kolo", "kitta", "tihlo",
    "telba", "chiko", "besso", "nifro", "kikil", "kwanta", "shekla", "cake", "pie", "ice cream", "cookies", "brownies", "cupcakes", "doughnuts", "pastries",
    "chocolate", "candy", "pudding", "custard", "mousse", "cheesecake", "tiramisu", "creme brulee", "flan", "panna cotta", "gelato", "sorbet", "macaron", "eclair", "tart",
    "chips", "popcorn", "pretzels", "nuts", "crackers", "trail mix", "beef jerky", "pork rinds", "rice cakes", "cereal bar", "energy bar", "protein shake", "smoothie", "milkshake", "bubble tea"
  ],

  "Desserts 🍰": [
    "cake", "cookie", "donut", "brownie", "ice cream", "pudding", "cheesecake", "cupcake", "pie", "tart", "chocolate", "candy", "jelly", "muffin", "macaron",
    "churros", "waffle", "mochi", "tiramisu", "popsicle", "sundae", "milkshake", "fudge", "caramel", "marshmallow", "custard", "gelato", "sorbet", "parfait", "pancake",
    "crepe", "profiterole", "eclair", "cannoli", "baklava", "panna cotta", "creme brulee", "trifle", "shortcake", "fruitcake", "red velvet cake", "carrot cake", "banana bread", "apple pie", "pumpkin pie",
    "lemon tart", "egg tart", "chocolate cake", "lava cake", "ice cream sandwich", "frozen yogurt", "cotton candy", "rock candy", "gummy bear", "jelly bean", "licorice", "toffee", "nougat", "marzipan", "praline",
    "truffle", "macaroon", "madeleine", "financier", "donut hole", "cinnamon roll", "sticky bun", "bread pudding", "rice pudding", "mango pudding", "grass jelly", "bean curd dessert", "tangyuan", "sesame ball", "egg waffle",
    "pineapple tart", "kueh", "ondeh ondeh", "cendol", "ice kacang", "bingsu", "dango", "dorayaki", "taiyaki", "castella", "mont blanc", "pavlova", "meringue", "flan", "tres leches",
    "chocolate mousse", "fruit tart", "caramel pudding", "vanilla pudding", "banana split", "peach cobbler", "halva", "key lime pie", "lemon meringue pie", "pecan pie", "sweet potato pie", "shoofly pie", "chess pie", "buttermilk pie", "coconut cream pie",
    "Boston cream pie", "whoopie pie", "moon pie", "hand pie", "empanada dulce", "turnover", "strudel", "danish", "cinnamon twist", "bear claw", "coffee cake", "crumb cake", "pound cake", "angel food cake", "sponge cake",
    "chiffon cake", "bundt cake", "sheet cake", "poke cake", "icebox cake", "flourless cake", "molten cake", "mug cake", "upside-down cake", "pineapple upside-down cake", "hummingbird cake", "red bean cake", "mung bean cake", "taro cake", "pandan cake",
    "roll cake", "Swiss roll", "Yule log", "buche de Noel", "roulade", "cream puff", "choux pastry", "beignet", "funnel cake", "elephant ear", "fried dough", "doughnut", "glaze", "frosting", "icing",
    "buttercream", "ganache", "whipped cream", "meringue kiss", "macaron shell", "fortune cookie", "almond cookie", "sugar cookie", "oatmeal cookie", "chocolate chip cookie", "peanut butter cookie", "snickerdoodle", "gingerbread", "shortbread", "biscotti",
    "ladyfinger", "amaretti", "pizzelle", "stroopwafel", "speculoos", "anise cookie", "pfeffernusse", "lebkuchen", "springerle", "krumkake", "rosette", "tuile", "langue de chat", "palmier", "cat tongue",
    "crostata", "sfogliatella", "zeppole", "babka", "kolache", "rugelach", "hamentashen", "sufganiyot", "filhós", "churro", "sopapilla", "bunuelo", "picarones", "loukoumades", "malasada",
    "gulab jamun", "jalebi", "rasgulla", "rasmalai", "barfi", "ladoo", "halwa", "kheer", "phirni", "kulfi", "falooda", "shrikhand", "sandesh", "cham cham", "pantua",
    "mochi ice cream", "daifuku", "manju", "yokan", "monaka", "anmitsu", "kakigori", "melon pan", "cream pan", "kuri manju", "imagawayaki", "obanyaki", "honey toast", "shaved ice", "halo-halo",
    "leche flan", "ube halaya", "bibingka", "puto", "kakanin", "sapin-sapin", "biko", "suman", "turon", "banana cue", "cassava cake", "maja blanca", "palitaw", "espasol", "pastillas",
    "banh flan", "che", "Vietnamese coffee jelly", "Thai mango sticky rice", "tub tim grob", "sankaya", "lot chong", "khanom chan", "khanom bua loy", "khanom krok", "thong yip", "foi thong", "med khanun", "khao tom mud", "bua loi",
    "kintsuba", "imagawayaki", "ningyo-yaki", "fuwafuwa pancake", "baumkuchen", "roll cake", "strawberry shortcake", "fruit sandwich", "cream anmitsu", "matcha parfait", "warabi mochi", "kuzumochi", "ohagi", "botamochi", "sakura mochi",
    "mooncake", "snow skin mooncake", "egg yolk pastry", "pineapple cake", "suncake", "wife cake", "husband cake", "sesame paste", "red bean soup", "tangyuan", "osmanthus jelly", "herbal jelly", "almond jelly", "mango pomelo sago", "tofu pudding",
    "affogato", "semifreddo", "cassata", "spumoni", "stracciatella", "tortoni", "baked Alaska", "banana foster", "crepes suzette", "cherries jubilee", "peach melba", "poire belle Helene", "profiteroles", "Paris-Brest", "Saint-Honore"
  ],

  "Drinks 🥤": [
    "water", "sparkling water", "mineral water", "spring water", "purified water", "tap water", "distilled water", "alkaline water", "coconut water", "rose water", "orange blossom water", "tonic water", "soda water", "club soda", "seltzer",
    "milk", "whole milk", "skim milk", "low-fat milk", "buttermilk", "chocolate milk", "strawberry milk", "vanilla milk", "condensed milk drink", "evaporated milk drink", "goat milk", "sheep milk", "buffalo milk", "camel milk", "yak milk",
    "soy milk", "almond milk", "oat milk", "rice milk", "cashew milk", "coconut milk drink", "hemp milk", "pea milk", "macadamia milk", "flax milk", "hazelnut milk", "quinoa milk", "spelt milk", "tiger nut milk", "horchata",
    "coffee", "espresso", "ristretto", "lungo", "americano", "long black", "short black", "cappuccino", "latte", "flat white", "macchiato", "mocha", "white coffee", "black coffee", "iced coffee",
    "cold brew", "nitro cold brew", "frappe", "frappuccino", "affogato", "Irish coffee", "Turkish coffee", "Greek coffee", "Vietnamese coffee", "egg coffee", "bulletproof coffee", "drip coffee", "pour-over", "French press", "espresso tonic",
    "red eye", "black eye", "dead eye", "caramel latte", "vanilla latte", "hazelnut latte", "pumpkin spice latte", "gingerbread latte", "mocha latte", "white mocha", "caramel macchiato", "vanilla macchiato", "cortado", "cafe au lait", "cafe con leche",
    "tea", "black tea", "green tea", "white tea", "oolong tea", "pu-erh", "matcha", "sencha", "gyokuro", "hojicha", "genmaicha", "jasmine tea", "earl grey", "English breakfast", "Irish breakfast",
    "Darjeeling", "Assam", "Ceylon", "chai", "masala chai", "Thai tea", "Hong Kong milk tea", "teh tarik", "bubble tea", "milk tea", "taro milk tea", "brown sugar milk tea", "fruit tea", "passionfruit tea", "peach tea",
    "lemon tea", "iced tea", "sweet tea", "unsweet tea", "herbal tea", "peppermint tea", "chamomile tea", "rooibos", "hibiscus tea", "rose tea", "chrysanthemum tea", "ginger tea", "turmeric tea", "licorice tea", "fennel tea",
    "lemon balm tea", "valerian tea", "yerba mate", "guayusa", "kombucha", "kefir", "matcha latte", "chai latte", "dirty chai", "London fog", "Thai iced tea", "boba milk tea", "boba", "popping boba", "jelly drink",
    "juice", "orange juice", "apple juice", "grape juice", "mango juice", "pineapple juice", "tomato juice", "cranberry juice", "lime juice", "lemon juice", "grapefruit juice", "pomegranate juice", "cherry juice", "berry juice", "strawberry juice",
    "raspberry juice", "blueberry juice", "blackcurrant juice", "redcurrant juice", "elderberry juice", "acai juice", "goji juice", "noni juice", "aloe vera juice", "cactus juice", "cucumber juice", "carrot juice", "beet juice", "celery juice", "spinach juice",
    "kale juice", "wheatgrass juice", "barley grass juice", "sugarcane juice", "passionfruit juice", "guava juice", "papaya juice", "lychee juice", "dragonfruit juice", "starfruit juice", "kiwi juice", "peach juice", "pear juice", "apricot juice", "plum juice",
    "prune juice", "fig juice", "date juice", "tamarind juice", "hibiscus juice", "sorrel drink", "agua fresca", "licuado", "smoothie", "green smoothie", "fruit smoothie", "protein shake", "meal replacement shake", "milkshake", "malt shake",
    "thickshake", "iced blended coffee", "slushie", "slush", "granita", "snow cone", "shaved ice", "ice cream float", "root beer float", "coke float", "soda", "cola", "Coca-Cola", "Pepsi", "root beer",
    "ginger ale", "ginger beer", "lemon-lime soda", "Sprite", "7 Up", "orange soda", "grape soda", "cream soda", "cherry soda", "vanilla soda", "Dr Pepper", "Mountain Dew", "Fanta", "Mirinda", "Schweppes",
    "sparkling mineral water", "flavored sparkling water", "LaCroix", "Perrier", "San Pellegrino", "sparkling lemonade", "Italian soda", "egg cream", "lemonade", "pink lemonade", "strawberry lemonade", "raspberry lemonade", "mint lemonade", "ginger lemonade", "cucumber lemonade",
    "lavender lemonade", "peach lemonade", "mango lemonade", "blue lemonade", "fruit punch", "party punch", "punch", "wassail", "apple cider", "mulled cider", "spiced cider", "eggnog", "coquito", "atole", "champurrado",
    "ponche", "glogg", "mulled wine", "mulled mead", "butterbeer", "hot chocolate", "cocoa", "white hot chocolate", "Mexican hot chocolate", "chocolate caliente", "chocolate milk", "Ovaltine", "Milo", "hot malt", "malted milk",
    "sports drink", "Gatorade", "Powerade", "energy drink", "Red Bull", "Monster", "Rockstar", "Celsius", "Prime", "electrolyte drink", "pickle juice", "hydration drink", "vitamin water", "protein water", "collagen water",
    "flavored water", "infused water", "detox water", "cucumber water", "lemon water", "mint water", "berry water", "fruit-infused water", "spa water", "rose water drink", "orange water", "watermelon water", "basil water", "ginger water", "chia water",
    "mocktail", "virgin mojito", "virgin piña colada", "virgin margarita", "Shirley Temple", "Roy Rogers", "Arnold Palmer", "virgin sangria", "non-alcoholic punch", "non-alcoholic beer", "non-alcoholic wine", "non-alcoholic cider", "non-alcoholic champagne", "non-alcoholic cocktail", "virgin daiquiri",
    "beer", "lager", "ale", "IPA", "stout", "porter", "pilsner", "wheat beer", "sour beer", "shandy", "radler", "cider", "hard cider", "pear cider", "scrumpy",
    "wine", "red wine", "white wine", "rosé", "sparkling wine", "champagne", "prosecco", "cava", "port", "sherry", "vermouth", "sake", "soju", "plum wine", "rice wine",
    "vodka", "gin", "rum", "tequila", "whiskey", "bourbon", "scotch", "brandy", "cognac", "mezcal", "absinthe", "liqueur", "bitters", "schnapps", "aquavit",
    "cocktail", "martini", "margarita", "mojito", "piña colada", "daiquiri", "cosmopolitan", "manhattan", "old fashioned", "negroni", "whiskey sour", "gin and tonic", "bloody mary", "moscow mule", "long island iced tea",
    "screwdriver", "tequila sunrise", "white Russian", "black Russian", "espresso martini", "aperol spritz", "bellini", "mimosa", "sangria", "caipirinha", "mai tai", "zombie", "hurricane", "sidecar", "gimlet",
    "paloma", "dark and stormy", "blue lagoon", "sex on the beach", "bahama mama", "Singapore sling", "Tom Collins", "French 75", "kir royale", "americano", "boulevardier", "sazerac", "mint julep", "caipiroska", "lemon drop",
    "appletini", "chocolate martini", "dirty martini", "Gibson", "vesper", "aviation", "last word", "corpse reviver", "pisco sour", "rum punch", "planter's punch", "tiki drink", "scorpion bowl", "fog cutter", "navy grog",
    "hot toddy", "buttered rum", "mulled wine", "mulled cider", "hot buttered rum", "Tom and Jerry", "eggnog", "coquito", "ponche", "wassail", "bishop", "negus", "smoking bishop", "mulled ale", "ale flip",
    "iced tea", "sweet tea", "unsweet tea", "sun tea", "refrigerator tea", "cold brew tea", "bubble tea", "fruit boba", "cheese foam tea", "milk cap tea", "salted cheese tea", "yakult tea", "yogurt drink", "drinking yogurt", "lassi",
    "mango lassi", "rose lassi", "salted lassi", "sweet lassi", "ayran", "doogh", "kefir", "buttermilk", "chaas", "thandai", "falooda", "sherbet", "sorbet drink", "sharbat", "sekanjabin",
    "agua de jamaica", "agua de horchata", "agua de tamarindo", "agua de limón", "agua de melón", "agua de sandía", "agua de piña", "agua de fresa", "agua de mango", "agua de coco", "agua de arroz", "agua de canela", "agua de pepino", "agua de chia", "agua de flor de Jamaica",
    "bubble tea", "boba tea", "milk tea", "fruit tea", "cheese tea", "brown sugar boba", "tiger milk tea", "matcha boba", "taro boba", "Thai boba", "honey boba", "lychee boba", "mango boba", "passionfruit boba", "strawberry boba",
    "smoothie", "green smoothie", "fruit smoothie", "berry smoothie", "banana smoothie", "mango smoothie", "strawberry smoothie", "pineapple smoothie", "kale smoothie", "acai smoothie", "pitaya smoothie", "avocado smoothie", "peanut butter smoothie", "chocolate smoothie", "coffee smoothie",
    "milkshake", "chocolate milkshake", "vanilla milkshake", "strawberry milkshake", "banana milkshake", "Oreo milkshake", "caramel milkshake", "coffee milkshake", "malted milkshake", "peanut butter milkshake", "salted caramel milkshake", "matcha milkshake", "taro milkshake", "mango milkshake", "blueberry milkshake",
    "frappe", "mocha frappe", "caramel frappe", "coffee frappe", "chocolate frappe", "vanilla frappe", "Oreo frappe", "matcha frappe", "taro frappe", "strawberry frappe", "mango frappe", "cookies and cream frappe", "salted caramel frappe", "hazelnut frappe", "mint frappe",
    "iced coffee", "iced latte", "iced mocha", "iced macchiato", "iced americano", "iced espresso", "iced cold brew", "iced vanilla latte", "iced caramel latte", "iced hazelnut latte", "iced matcha latte", "iced chai latte", "iced Thai tea", "iced milk tea", "iced boba"
  ],

  "Singapore Food 🇸🇬": [
    "海南鸡饭", "辣椒螃蟹", "肉骨茶", "叻沙", "沙爹", "咖椰吐司", "拉茶", "福建面", "炒粿条", "萝卜糕", "水粿", "笋粿", "红龟粿", "咖喱鱼头", "黑胡椒螃蟹",
    "麦片虾", "椰浆饭", "乌打", "罗惹", "薄饼", "鱼圆面", "酿豆腐", "肉脞面", "板面", "云吞面", "虾面", "卤面", "咖喱面", "米暹", "马来卤面",
    "印度煎饼", "Kopi", "Kopi O", "Kopi C", "Milo Dinosaur", "Bandung", "甘蔗汁", "酸柑水", "红豆冰", "珍多", "摩摩喳喳", "榴莲", "山竹", "红毛丹", "龙眼",
    "荔枝", "椰子", "甘蔗", "黄梨", "西瓜", "木瓜", "芒果", "香蕉", "番石榴", "莲雾", "杨桃", "红毛榴莲", "菠萝蜜", "尖不辣", "杜古",
    "冷刹", "龙贡", "兰撒", "蛇皮果", "人参果", "百香果", "火龙果", "番荔枝", "释迦", "烧鸡饭", "白鸡饭", "油鸡饭", "叉烧饭", "烧肉饭", "咖喱鸡饭",
    "椰浆饭", "叻沙", "咖喱面", "虾面", "福建面", "炒粿条", "炒米粉", "炒饭", "菜头粿", "水粿", "笋粿", "韭菜粿", "红龟粿", "发糕", "鸡蛋糕",
    "千层糕", "九层糕", "糯米鸡", "荷叶饭", "生煎包", "灌汤包", "叉烧包", "奶黄包", "莲蓉包", "豆沙包", "菜肉包", "银丝卷", "窝窝头", "贴饼子", "菜团子",
    "沙爹", "烤鸡翅", "烤鱼", "烤虾", "烤鱿鱼", "烤羊肉", "烤牛肉", "烤猪肉", "烤玉米", "烤番薯", "烤马铃薯", "烤面包", "烤棉花糖", "烤鱼饼", "烤鱼丸",
    "鱼圆", "鱼饼", "鱼丸", "虾丸", "牛肉丸", "猪肉丸", "鸡肉丸", "墨鱼丸", "章鱼丸", "豆腐丸", "蔬菜丸", "香菇丸", "鱼面", "虾面", "肉脞面",
    "板面", "面粉粿", "东炎面", "冬阴功面", "酸辣面", "清汤面", "干捞面", "云吞面", "水饺面", "炸酱面", "红烧面", "咖喱鸡面", "咖喱鱼头面", "叻沙面", "虾米面"
  ],

  "Fast Food 🍟": [
    "hamburger", "cheeseburger", "double cheeseburger", "bacon burger", "chicken burger", "fish burger", "veggie burger", "hot dog", "corn dog", "chicken nuggets",
    "chicken wings", "fried chicken", "chicken tenders", "chicken popcorn", "french fries", "curly fries", "waffle fries", "potato wedges", "hash browns", "onion rings",
    "mozzarella sticks", "jalapeno poppers", "nachos", "tacos", "burritos", "quesadillas", "pizza", "pepperoni pizza", "cheese pizza", "hawaiian pizza",
    "sandwiches", "club sandwich", "BLT", "submarine sandwich", "wrap", "pita", "gyro", "falafel", "hot wings", "buffalo wings",
    "barbecue wings", "chicken sandwich", "fish sandwich", "egg muffin", "sausage muffin", "pancakes", "waffles", "french toast", "hash brown", "breakfast burrito",
    "milkshake", "smoothie", "soft drink", "cola", "lemonade", "iced tea", "coffee", "orange juice", "apple pie", "ice cream",
    "sundae", "cone", "sundae", "float", "mcflurry", "blizzard", "sundae", "apple slices", "fruit cup", "yogurt parfait",
    "ketchup", "mustard", "mayonnaise", "barbecue sauce", "ranch", "sweet chili", "hot sauce", "salt", "pepper", "napkins",
    "straw", "cup lid", "paper bag", "plastic bag", "tray", "drive-thru", "counter", "menu", "combo meal", "value meal",
    "kids meal", "happy meal", "upsize", "takeout", "dine-in", "delivery", "pickup", "order", "cashier", "queue"
  ],

  "Kitchen 🍳": [
    "kitchen", "stove", "gas stove", "electric stove", "induction cooker", "microwave", "oven", "toaster", "rice cooker", "pressure cooker",
    "slow cooker", "air fryer", "blender", "juicer", "food processor", "coffee maker", "electric kettle", "hot water dispenser", "frying pan", "wok",
    "saucepan", "stockpot", "steamer", "clay pot", "baking tray", "grill", "grill rack", "steamer basket", "bamboo steamer", "electric steamer",
    "cutting board", "chef's knife", "paring knife", "peeler", "scissors", "grater", "mortar and pestle", "mixing bowl", "measuring cup", "measuring spoons",
    "kitchen scale", "thermometer", "timer", "bottle opener", "can opener", "garlic press", "lemon squeezer", "strainer", "colander", "ladle",
    "spatula", "tongs", "chopsticks", "spoon", "fork", "knife", "plate", "bowl", "saucer", "cup",
    "mug", "glass", "teapot", "kettle", "thermos", "lunch box", "bento box", "food container", "cling wrap", "aluminum foil",
    "baking paper", "kitchen towel", "dishcloth", "sponge", "steel wool", "dish soap", "dishwasher liquid", "trash can", "garbage bag", "refrigerator",
    "freezer", "freezer compartment", "fridge compartment", "storage cabinet", "spice rack", "knife block", "pot lid holder", "drying rack", "dish rack", "cup rack",
    "hooks", "drawer", "cupboard", "countertop", "sink", "faucet", "drain", "garbage disposal", "range hood", "exhaust fan",
    "vent", "anti-slip mat", "apron", "gloves", "heat pad", "oven mitt", "kitchen towel", "hand towel", "cleaning agent", "disinfectant",
    "degreaser", "scouring powder", "baking soda", "white vinegar", "citric acid", "bleach", "rubber gloves", "mask", "hat", "hairnet",
    "chef uniform", "chef hat", "sleeve covers", "non-slip shoes", "kitchen safety", "fire prevention", "fire extinguisher", "first aid kit", "recipe", "menu",
    "napkin", "tablecloth", "placemat", "candlestick", "vase", "condiment bottle", "oil bottle", "vinegar bottle", "soy sauce bottle", "pepper shaker",
    "salt shaker", "sugar jar", "tea tin", "coffee jar", "sealed jar", "storage jar", "storage box", "basket", "tray", "cutting board rack"
  ]
};
